# Nome da apliucação
spring.application.name=clientes

# Banco H2 persistente
spring.datasource.url=jdbc:h2:file:./data/clientesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Config banco inicial
spring.sql.init.mode=always

# Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Evitar erro do H2
spring.jpa.defer-datasource-initialization=true
